-- MySQL Script generated by MySQL Workbench
-- 09/14/14 21:24:32
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema canudosway
-- -----------------------------------------------------
-- 
-- 
CREATE SCHEMA IF NOT EXISTS `canudosway` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `canudosway` ;

-- -----------------------------------------------------
-- Table `canudosway`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canudosway`.`aluno` ;

CREATE TABLE IF NOT EXISTS `canudosway`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canudosway`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canudosway`.`curso` ;

CREATE TABLE IF NOT EXISTS `canudosway`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canudosway`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canudosway`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `canudosway`.`disciplina` (
  `id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `nome_disciplina` VARCHAR(100) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `horas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_disciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canudosway`.`aluno_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canudosway`.`aluno_curso` ;

CREATE TABLE IF NOT EXISTS `canudosway`.`aluno_curso` (
  `id_aluno_curso` INT NOT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_aluno_curso`),
  INDEX `aluno_idx` (`id_aluno` ASC),
  INDEX `curso_idx` (`id_curso` ASC),
  CONSTRAINT `aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `canudosway`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `canudosway`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canudosway`.`curso_disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canudosway`.`curso_disciplina` ;

CREATE TABLE IF NOT EXISTS `canudosway`.`curso_disciplina` (
  `id_curso_disciplina` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_curso_disciplina`),
  INDEX `curso_idx` (`id_curso` ASC),
  INDEX `disciplina_idx` (`id_disciplina` ASC),
  CONSTRAINT `curso_disciplina`
    FOREIGN KEY (`id_curso`)
    REFERENCES `canudosway`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `canudosway`.`disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
